export const AUDIT_ACTIONS = {
  ACCOUNT_DATA_DOWNLOADED: "account.data_downloaded",
  ACCOUNT_DELETED: "account.deleted",
  ACCOUNT_DELETE_REQUESTED: "account.delete_requested",
  ACCOUNT_PASSWORD_CHANGED: "account.password_changed",
  AUTH_LOGIN_FAILED: "auth.login.failed",
  AUTH_LOGIN_SUCCESS: "auth.login.success",
  AUTH_LOGOUT: "auth.logout",
  AUTH_REGISTER_SUCCESS: "auth.register.success",
  BUDGET_CREATED: "budget.created",
  BUDGET_DELETED: "budget.deleted",
  BUDGET_UPDATED: "budget.updated",
  CATEGORY_CREATED: "category.created",
  CATEGORY_DELETED: "category.deleted",
  CATEGORY_UPDATED: "category.updated",
  EXPORT_COMPLETED: "export.completed",
  EXPORT_DOWNLOADED: "export.downloaded",
  EXPORT_FAILED: "export.failed",
  EXPORT_REQUESTED: "export.requested",
  IMPORT_CANCELLED: "import.cancelled",
  IMPORT_COMPLETED: "import.completed",
  IMPORT_COMPLETED_WITH_ERRORS: "import.completed_with_errors",
  IMPORT_CONFIRMED: "import.confirmed",
  IMPORT_FAILED: "import.failed",
  IMPORT_PREVIEW_GENERATED: "import.preview_generated",
  IMPORT_UPLOADED: "import.uploaded",
  PRIVACY_MODE_DISABLED: "privacy_mode.disabled",
  PRIVACY_MODE_ENABLED: "privacy_mode.enabled",
  RECURRING_TRANSACTION_CANCELLED: "recurring_transaction.cancelled",
  RECURRING_TRANSACTION_CREATED: "recurring_transaction.created",
  RECURRING_TRANSACTION_GENERATED: "recurring_transaction.generated",
  RECURRING_TRANSACTION_PAUSED: "recurring_transaction.paused",
  RECURRING_TRANSACTION_RESUMED: "recurring_transaction.resumed",
  RECURRING_TRANSACTION_UPDATED: "recurring_transaction.updated",
  REPORT_EXPORTED: "export.created",
  SESSION_CREATED: "session.created",
  SESSION_LOGOUT_OTHERS: "session.logout_others",
  SESSION_REVOKED: "session.revoked",
  SMART_NOTIFICATION_CREATED: "smart_notification.created",
  TWO_FACTOR_DISABLED: "two_factor.disabled",
  TWO_FACTOR_ENABLED: "two_factor.enabled",
  TWO_FACTOR_LOGIN_FAILED: "two_factor.login_failed",
  TWO_FACTOR_RECOVERY_CODE_USED: "two_factor.recovery_code_used",
  TWO_FACTOR_RECOVERY_CODES_REGENERATED: "two_factor.recovery_codes_regenerated",
  TWO_FACTOR_SETUP_CANCELLED: "two_factor.setup_cancelled",
  TWO_FACTOR_SETUP_FAILED: "two_factor.setup_failed",
  TWO_FACTOR_SETUP_STARTED: "two_factor.setup_started",
  TRANSACTION_CREATED: "transaction.created",
  TRANSACTION_DELETED: "transaction.deleted",
  TRANSACTION_UPDATED: "transaction.updated",
  WALLET_CREATED: "account.created",
  WALLET_DELETED: "account.deleted",
  WALLET_UPDATED: "account.updated"
} as const;

export const AUDIT_ENTITY_TYPES = {
  BUDGET: "budget",
  CATEGORY: "category",
  EXPORT: "export",
  IMPORT: "import",
  NOTIFICATION: "notification",
  RECURRING_TRANSACTION: "recurring_transaction",
  SESSION: "session",
  TRANSACTION: "transaction",
  USER: "user",
  WALLET: "account"
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];
export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[keyof typeof AUDIT_ENTITY_TYPES];
