import { Router } from "express";

import { auditLogRouter } from "../modules/audit-logs/audit-log.routes";
import { aiRouter } from "../modules/ai/ai.routes";
import { authRouter } from "../modules/auth/auth.routes";
import { budgetRouter } from "../modules/budgets/budget.routes";
import { calendarRouter } from "../modules/calendar/calendar.routes";
import { categoryRouter } from "../modules/categories/category.routes";
import { dataExportRouter } from "../modules/data-exports/data-export.routes";
import { dataImportRouter } from "../modules/data-imports/data-import.routes";
import { dashboardRouter } from "../modules/dashboard/dashboard.routes";
import { debtRouter } from "../modules/debts/debt.routes";
import { financialHealthRouter } from "../modules/financial-health/financial-health.routes";
import { goalRouter } from "../modules/goals/goal.routes";
import { notificationRouter } from "../modules/notifications/notification.routes";
import { preferenceRouter } from "../modules/preferences/preference.routes";
import { recurringTransactionRouter } from "../modules/recurring-transactions/recurring-transaction.routes";
import { reportRouter } from "../modules/reports/report.routes";
import { securitySessionRouter } from "../modules/security-sessions/security-session.routes";
import { transactionRouter } from "../modules/transactions/transaction.routes";
import { walletRouter } from "../modules/wallets/wallet.routes";

export const apiRouter = Router();

apiRouter.use("/auth", authRouter);
apiRouter.use("/ai", aiRouter);
apiRouter.use("/wallets", walletRouter);
apiRouter.use("/categories", categoryRouter);
apiRouter.use("/transactions", transactionRouter);
apiRouter.use("/calendar", calendarRouter);
apiRouter.use("/budgets", budgetRouter);
apiRouter.use("/debts", debtRouter);
apiRouter.use("/goals", goalRouter);
apiRouter.use("/dashboard", dashboardRouter);
apiRouter.use("/financial-health", financialHealthRouter);
apiRouter.use("/reports", reportRouter);
apiRouter.use("/data-exports", dataExportRouter);
apiRouter.use("/data-imports", dataImportRouter);
apiRouter.use("/preferences", preferenceRouter);
apiRouter.use("/security", securitySessionRouter);
apiRouter.use("/recurring-transactions", recurringTransactionRouter);
apiRouter.use("/audit-logs", auditLogRouter);
apiRouter.use("/notifications", notificationRouter);
